groups:
  - id: general
    label: General Settings
    description: Configurações básicas do FRP Tunnel
    fields:
      - id: APP_PROFILE
        label: App Profile
        type: enum
        default: server
        required: true
        options: [server, client]
        max: 65535
      - id: FRP_BIND_ADDR
        label: Bind Address
        type: string
        default: 0.0.0.0
        required: false
      - id: FRP_BIND_PORT
        label: Bind Port
        type: integer
        default: 7000
        required: false
        min: 1
        max: 65535
      - id: FRP_TOKEN
        label: Token
        type: string
        default: changeme
        required: false
