services:
  server:
    image: snowdreamtech/frps:latest
    container_name: frp-server
    restart: "no"
    network_mode: host
    profiles: ["server"]
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./data:/etc/frp
      - ./logs:/var/log/frp
    environment:
      - FRP_BIND_ADDR=${FRP_BIND_ADDR:-0.0.0.0}
      - FRP_BIND_PORT=${FRP_BIND_PORT:-7000}
      - FRP_TOKEN=${FRP_TOKEN:-changeme}
      - FRP_TCP_MUX=true

  client:
    image: snowdreamtech/frpc:latest
    container_name: frp-client
    restart: "no"
    network_mode: host
    profiles: ["client"]
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./data:/etc/frp
      - ./logs:/var/log/frp
    environment:
      - FRP_TOKEN=${FRP_TOKEN:-changeme}
      - FRP_TCP_MUX=true