services:
  macos:
    image: container-apps/docker-osx-vnc:latest
    build:
      context: https://github.com/sickcodes/Docker-OSX.git#master:vnc-version
    container_name: ${CONTAINER_NAME:-macos-1}
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
      - SHORTNAME=${SHORTNAME:-sequoia}
      - RAM=${RAM:-4}
      - SMP=${SMP:-1}
      - CORES=${CORES:-1}
      - CPU=${CPU:-Haswell-noTSX}
      - CPUID_FLAGS=${CPUID_FLAGS:-kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on}
      - IMAGE_PATH=/storage/mac_hdd_ng.img
      - EXTRA=${EXTRA:-}
    privileged: true
    devices:
      - /dev/kvm
    ports:
      - "127.0.0.1:${HOST_VNC_PORT:-8888}:5999"
      - "${HOST_SSH_PORT:-50922}:10022"
    volumes:
      - ./macos:/storage
