services:
  macos:
    image: dockurr/macos:latest
    container_name: ${CONTAINER_NAME:-macos-1}
    restart: always
    stop_grace_period: 2m
    environment:
      - VERSION=${VERSION:-15}
      - MODEL=${MODEL:-iMacPro1,1}
      - DISK_SIZE=${DISK_SIZE:-64G}
      - RAM_SIZE=${RAM_SIZE:-4G}
      - CPU_CORES=${CPU_CORES:-2}
      - ARGUMENTS=${ARGUMENTS:-}
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "${HOST_VNC_PORT:-5900}:5900/tcp"
      - "${HOST_VNC_PORT:-5900}:5900/udp"
    volumes:
      - ./macos:/storage
